# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pyowm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(related_name='users', to='django_pyowm.Location'),
        ),
    ]
